#!/bin/sh

sudo pacman -Suy \
        arandr \
	alacritty \
        ccache \
	cppcheck \
	debugedit \
	dunst \
        fakeroot \
        feh \
        fish \
	exa \
        htop \
	jq \
	make \
	network-manager-applet \
	notification-daemon \
        obs-studio \
        ripgrep  \
        stalonetray  \
        workrave \
        xdotool 

# vpn
#     opensc \
#     openvpn
