#!/bin/sh

sudo pacman -Suy \
        arandr \
	alacritty \
        ccache \
	cppcheck \
	dunst \
        feh \
        fish \
	exa \
        htop \
	jq \
	notification-daemon \
        obs-studio \
        stalonetray 
